name: check-and-validate

on:
  # push:
  #   branches:
  #     - '**'
  #   paths:
  #     - "**/**/*.tf"
  pull_request:
    branches:
      - main

jobs:
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  # Event `pull_request`: Compare the last commit of the main branch or last remote commit of the PR branch -> to the current commit of a PR branch.
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Checking TF code
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: get changed dirs
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          dir_names: true
          dir_names_exclude_current_dir: true

      - name: setup tf
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: $TF_VERSION

        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 

      - name: fmt and validate
        run: |
          terraform version
          for dir in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "> CHANGED: $dir"
            echo "terraform -chdir=$dir fmt"
            echo "terraform -chdir=$dir validate"
          done
