name: plan

on:
  push:
    branches:
      - '**'
    paths:
      - "**/**/*.tf"
  # pull_request:
  #   branches:
  #     - main

env:
  TF_PLANS_FLDR: ./tf-plans
  TF_VERSION: "1.5.6"
  
jobs:
  code-check:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: actions on PR
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: get changed dirs
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          dir_names: true
          dir_names_exclude_current_dir: true

      - name: setup tf
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: $TF_VERSION

      - name: create tf-plans folder
        run: |
          mkdir -p $TF_PLANS_FLDR

      - name: tf plan
        run: |
          terraform version
          for dir in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "> CHANGED: $dir"
            export tf_plan=$(echo $dir | tr '/' '-')
            echo "tf_plan=$tf_plan"
            echo "terraform -chdir=$dir plan -out=$TF_PLANS_FLDR/$tf_plan.tfplan"
            echo "content" > $TF_PLANS_FLDR/$tf_plan.tfplan
          done

      - name: tf apply
        run: |
          for tfplan in $(ls $TF_PLANS_FLDR); do
            echo "terraform apply -auto-approve $TF_PLANS_FLDR/$tfplan"
          done
