name: plan

on:
  push:
    branches:
      - '**'
    paths:
      - "**/**/*.tf"
  # pull_request:
  #   branches:
  #     - main

env:
  # TF_PLANS_FLDR: ./tf-plans
  TF_PLAN_NAME: tfplan.file
  TF_VER: "1.5.6"
  
jobs:
  code-check:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: actions on PR

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: setup AWS profile
        run: |
          mkdir -p ~/.aws/
          touch ~/.aws/credentials
    
          cat <<EOF>~/.aws/credentials
          [vinco-tf-dev]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key =  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF

      - name: get changed dirs
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          dir_names: true
          dir_names_exclude_current_dir: true

      - name: setup tf
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: $TF_VER

      - name: tf init and plan
        run: |
          terraform version
          for dir in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "[CHANGED]: $dir"
            echo "terraform -chdir=$dir init -backend-config=../config.tfbackend"
            echo "terraform -chdir=$dir plan -var-file ../env.tfvars -out=$TF_PLAN_NAME"
            # echo "content" > $TF_PLANS_FLDR/$tf_plan.tfplan
          done


      - name: tf apply
        run: |
          for dir in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "terraform -chdir=$dir apply $TF_PLAN_NAME"
          done
          cat ~/.aws/credentials

